In [17]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [18]:
dataframe=pd.read_csv("iris_train_features.csv",header=None)
dataset=dataframe.values
X=dataset[:,0:4].astype(float)

In [19]:
dataframe=pd.read_csv("iris_train_label.csv", header=None)
dataset=dataframe.values
Y=dataset[:,0:3].astype(int)

In [20]:
input_layer=1
#hidden_layer1=1
#hiddden_layer2=4
output_layer=3

In [27]:
model=tf.keras.Sequential();
model.add(tf.keras.layers.Dense(input_layer,input_shape=(4,),name='input_layer',activation=tf.nn.relu,kernel_regularizer='l1'))
model.add(tf.keras.layers.Dense(output_layer,name='out_layer',activation='softmax',kernel_regularizer='l1'))
model.summary()
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
#writer=tf.summary.FileWriter('./graphs', tf.get_default_graph()))
model.fit(X,Y,epochs=1000,batch_size=105)
model.get_weights()



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 1)                 5         
_________________________________________________________________
out_layer (Dense)            (None, 3)                 6         
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
105/105 [==============================] - 3s 29ms/step - loss: 6.0798 - acc: 0.3429
Epoch 2/1000
105/105 [==============================] - 0s 133us/step - loss: 6.0545 - acc: 0.3429
Epoch 3/1000
105/105 [==============================] - 0s 57us/step - loss: 6.0293 - acc: 0.3429
Epoch 4/1000
105/105 [==============================] - 0s 914us/step - loss: 6.0042 - acc: 0.3429
Epoch 5/1000
105/105 [==============================] - 0s 76us/step - loss: 5.9791 - acc: 0.3429
Epoch 6/1000
105/105 [============================

Epoch 78/1000
105/105 [==============================] - 0s 38us/step - loss: 4.3165 - acc: 0.3429
Epoch 79/1000
105/105 [==============================] - 0s 419us/step - loss: 4.2963 - acc: 0.3429
Epoch 80/1000
105/105 [==============================] - 0s 210us/step - loss: 4.2762 - acc: 0.3429
Epoch 81/1000
105/105 [==============================] - 0s 67us/step - loss: 4.2561 - acc: 0.3429
Epoch 82/1000
105/105 [==============================] - 0s 143us/step - loss: 4.2361 - acc: 0.3429
Epoch 83/1000
105/105 [==============================] - 0s 229us/step - loss: 4.2162 - acc: 0.3429
Epoch 84/1000
105/105 [==============================] - 0s 86us/step - loss: 4.1964 - acc: 0.3429
Epoch 85/1000
105/105 [==============================] - 0s 86us/step - loss: 4.1766 - acc: 0.3429
Epoch 86/1000
105/105 [==============================] - 0s 143us/step - loss: 4.1569 - acc: 0.3429
Epoch 87/1000
105/105 [==============================] - 0s 76us/step - loss: 4.1373 - acc: 0.3429
Epoch

Epoch 160/1000
105/105 [==============================] - 0s 48us/step - loss: 2.9089 - acc: 0.3429
Epoch 161/1000
105/105 [==============================] - 0s 114us/step - loss: 2.8949 - acc: 0.3429
Epoch 162/1000
105/105 [==============================] - 0s 48us/step - loss: 2.8810 - acc: 0.3429
Epoch 163/1000
105/105 [==============================] - 0s 200us/step - loss: 2.8672 - acc: 0.3429
Epoch 164/1000
105/105 [==============================] - 0s 57us/step - loss: 2.8535 - acc: 0.3429
Epoch 165/1000
105/105 [==============================] - 0s 219us/step - loss: 2.8399 - acc: 0.3429
Epoch 166/1000
105/105 [==============================] - 0s 124us/step - loss: 2.8263 - acc: 0.3429
Epoch 167/1000
105/105 [==============================] - 0s 324us/step - loss: 2.8128 - acc: 0.3429
Epoch 168/1000
105/105 [==============================] - 0s 200us/step - loss: 2.7994 - acc: 0.3429
Epoch 169/1000
105/105 [==============================] - 0s 314us/step - loss: 2.7861 - acc: 

Epoch 242/1000
105/105 [==============================] - 0s 124us/step - loss: 2.0222 - acc: 0.3429
Epoch 243/1000
105/105 [==============================] - 0s 86us/step - loss: 2.0145 - acc: 0.3429
Epoch 244/1000
105/105 [==============================] - 0s 86us/step - loss: 2.0068 - acc: 0.3429
Epoch 245/1000
105/105 [==============================] - 0s 124us/step - loss: 1.9991 - acc: 0.3429
Epoch 246/1000
105/105 [==============================] - 0s 57us/step - loss: 1.9916 - acc: 0.3429
Epoch 247/1000
105/105 [==============================] - 0s 390us/step - loss: 1.9841 - acc: 0.3429
Epoch 248/1000
105/105 [==============================] - 0s 76us/step - loss: 1.9767 - acc: 0.3429
Epoch 249/1000
105/105 [==============================] - 0s 67us/step - loss: 1.9693 - acc: 0.3429
Epoch 250/1000
105/105 [==============================] - 0s 114us/step - loss: 1.9620 - acc: 0.3429
Epoch 251/1000
105/105 [==============================] - 0s 86us/step - loss: 1.9548 - acc: 0.3

Epoch 324/1000
105/105 [==============================] - 0s 486us/step - loss: 1.5770 - acc: 0.2952
Epoch 325/1000
105/105 [==============================] - 0s 257us/step - loss: 1.5735 - acc: 0.2857
Epoch 326/1000
105/105 [==============================] - 0s 48us/step - loss: 1.5701 - acc: 0.2857
Epoch 327/1000
105/105 [==============================] - 0s 114us/step - loss: 1.5667 - acc: 0.2857
Epoch 328/1000
105/105 [==============================] - 0s 143us/step - loss: 1.5633 - acc: 0.2857
Epoch 329/1000
105/105 [==============================] - 0s 190us/step - loss: 1.5600 - acc: 0.2857
Epoch 330/1000
105/105 [==============================] - 0s 143us/step - loss: 1.5567 - acc: 0.2857
Epoch 331/1000
105/105 [==============================] - 0s 276us/step - loss: 1.5534 - acc: 0.2857
Epoch 332/1000
105/105 [==============================] - 0s 57us/step - loss: 1.5502 - acc: 0.2857
Epoch 333/1000
105/105 [==============================] - 0s 781us/step - loss: 1.5470 - acc:

Epoch 406/1000
105/105 [==============================] - 0s 524us/step - loss: 1.3867 - acc: 0.0571
Epoch 407/1000
105/105 [==============================] - 0s 200us/step - loss: 1.3853 - acc: 0.0571
Epoch 408/1000
105/105 [==============================] - 0s 257us/step - loss: 1.3838 - acc: 0.0571
Epoch 409/1000
105/105 [==============================] - 0s 410us/step - loss: 1.3824 - acc: 0.0667
Epoch 410/1000
105/105 [==============================] - 0s 219us/step - loss: 1.3810 - acc: 0.0667
Epoch 411/1000
105/105 [==============================] - 0s 305us/step - loss: 1.3797 - acc: 0.0667
Epoch 412/1000
105/105 [==============================] - 0s 324us/step - loss: 1.3783 - acc: 0.0762
Epoch 413/1000
105/105 [==============================] - 0s 48us/step - loss: 1.3770 - acc: 0.0857
Epoch 414/1000
105/105 [==============================] - 0s 95us/step - loss: 1.3756 - acc: 0.0857
Epoch 415/1000
105/105 [==============================] - 0s 48us/step - loss: 1.3743 - acc: 

Epoch 488/1000
105/105 [==============================] - 0s 952us/step - loss: 1.3053 - acc: 0.0857
Epoch 489/1000
105/105 [==============================] - 0s 162us/step - loss: 1.3046 - acc: 0.0857
Epoch 490/1000
105/105 [==============================] - 0s 86us/step - loss: 1.3039 - acc: 0.0857
Epoch 491/1000
105/105 [==============================] - 0s 124us/step - loss: 1.3032 - acc: 0.0952
Epoch 492/1000
105/105 [==============================] - 0s 114us/step - loss: 1.3025 - acc: 0.1048
Epoch 493/1000
105/105 [==============================] - 0s 86us/step - loss: 1.3018 - acc: 0.0952
Epoch 494/1000
105/105 [==============================] - 0s 57us/step - loss: 1.3011 - acc: 0.0952
Epoch 495/1000
105/105 [==============================] - 0s 229us/step - loss: 1.3005 - acc: 0.0952
Epoch 496/1000
105/105 [==============================] - 0s 429us/step - loss: 1.2998 - acc: 0.1143
Epoch 497/1000
105/105 [==============================] - 0s 314us/step - loss: 1.2991 - acc: 

Epoch 570/1000
105/105 [==============================] - 0s 95us/step - loss: 1.2607 - acc: 0.1619
Epoch 571/1000
105/105 [==============================] - 0s 238us/step - loss: 1.2603 - acc: 0.1619
Epoch 572/1000
105/105 [==============================] - 0s 143us/step - loss: 1.2599 - acc: 0.1619
Epoch 573/1000
105/105 [==============================] - 0s 343us/step - loss: 1.2595 - acc: 0.1619
Epoch 574/1000
105/105 [==============================] - 0s 48us/step - loss: 1.2591 - acc: 0.1619
Epoch 575/1000
105/105 [==============================] - 0s 38us/step - loss: 1.2587 - acc: 0.1619
Epoch 576/1000
105/105 [==============================] - 0s 267us/step - loss: 1.2583 - acc: 0.1619
Epoch 577/1000
105/105 [==============================] - 0s 48us/step - loss: 1.2579 - acc: 0.1619
Epoch 578/1000
105/105 [==============================] - 0s 86us/step - loss: 1.2576 - acc: 0.1619
Epoch 579/1000
105/105 [==============================] - 0s 248us/step - loss: 1.2572 - acc: 0.

Epoch 652/1000
105/105 [==============================] - 0s 200us/step - loss: 1.2319 - acc: 0.1143
Epoch 653/1000
105/105 [==============================] - 0s 105us/step - loss: 1.2316 - acc: 0.1238
Epoch 654/1000
105/105 [==============================] - 0s 124us/step - loss: 1.2313 - acc: 0.1238
Epoch 655/1000
105/105 [==============================] - 0s 181us/step - loss: 1.2310 - acc: 0.1238
Epoch 656/1000
105/105 [==============================] - 0s 95us/step - loss: 1.2307 - acc: 0.1238
Epoch 657/1000
105/105 [==============================] - 0s 76us/step - loss: 1.2303 - acc: 0.1238
Epoch 658/1000
105/105 [==============================] - 0s 629us/step - loss: 1.2300 - acc: 0.1238
Epoch 659/1000
105/105 [==============================] - 0s 76us/step - loss: 1.2297 - acc: 0.1333
Epoch 660/1000
105/105 [==============================] - 0s 333us/step - loss: 1.2294 - acc: 0.1238
Epoch 661/1000
105/105 [==============================] - 0s 171us/step - loss: 1.2291 - acc: 

Epoch 734/1000
105/105 [==============================] - 0s 48us/step - loss: 1.2086 - acc: 0.2381
Epoch 735/1000
105/105 [==============================] - 0s 171us/step - loss: 1.2084 - acc: 0.2381
Epoch 736/1000
105/105 [==============================] - 0s 29us/step - loss: 1.2081 - acc: 0.2381
Epoch 737/1000
105/105 [==============================] - 0s 57us/step - loss: 1.2079 - acc: 0.2381
Epoch 738/1000
105/105 [==============================] - 0s 314us/step - loss: 1.2076 - acc: 0.2381
Epoch 739/1000
105/105 [==============================] - 0s 57us/step - loss: 1.2074 - acc: 0.2381
Epoch 740/1000
105/105 [==============================] - 0s 67us/step - loss: 1.2071 - acc: 0.2381
Epoch 741/1000
105/105 [==============================] - 0s 57us/step - loss: 1.2069 - acc: 0.2381
Epoch 742/1000
105/105 [==============================] - 0s 38us/step - loss: 1.2066 - acc: 0.2381
Epoch 743/1000
105/105 [==============================] - 0s 29us/step - loss: 1.2064 - acc: 0.238

Epoch 816/1000
105/105 [==============================] - 0s 38us/step - loss: 1.1897 - acc: 0.2952
Epoch 817/1000
105/105 [==============================] - 0s 95us/step - loss: 1.1895 - acc: 0.2952
Epoch 818/1000
105/105 [==============================] - 0s 48us/step - loss: 1.1893 - acc: 0.2952
Epoch 819/1000
105/105 [==============================] - 0s 114us/step - loss: 1.1891 - acc: 0.3048
Epoch 820/1000
105/105 [==============================] - 0s 314us/step - loss: 1.1889 - acc: 0.3048
Epoch 821/1000
105/105 [==============================] - 0s 105us/step - loss: 1.1887 - acc: 0.3048
Epoch 822/1000
105/105 [==============================] - 0s 67us/step - loss: 1.1884 - acc: 0.3048
Epoch 823/1000
105/105 [==============================] - 0s 390us/step - loss: 1.1882 - acc: 0.3048
Epoch 824/1000
105/105 [==============================] - 0s 114us/step - loss: 1.1880 - acc: 0.3048
Epoch 825/1000
105/105 [==============================] - 0s 48us/step - loss: 1.1878 - acc: 0.

Epoch 898/1000
105/105 [==============================] - 0s 76us/step - loss: 1.1719 - acc: 0.3143
Epoch 899/1000
105/105 [==============================] - 0s 267us/step - loss: 1.1717 - acc: 0.3143
Epoch 900/1000
105/105 [==============================] - 0s 143us/step - loss: 1.1715 - acc: 0.3143
Epoch 901/1000
105/105 [==============================] - 0s 38us/step - loss: 1.1713 - acc: 0.3143
Epoch 902/1000
105/105 [==============================] - 0s 190us/step - loss: 1.1711 - acc: 0.3143
Epoch 903/1000
105/105 [==============================] - 0s 248us/step - loss: 1.1708 - acc: 0.3143
Epoch 904/1000
105/105 [==============================] - 0s 333us/step - loss: 1.1706 - acc: 0.3143
Epoch 905/1000
105/105 [==============================] - 0s 38us/step - loss: 1.1704 - acc: 0.3143
Epoch 906/1000
105/105 [==============================] - 0s 267us/step - loss: 1.1702 - acc: 0.3143
Epoch 907/1000
105/105 [==============================] - 0s 48us/step - loss: 1.1700 - acc: 0

Epoch 980/1000
105/105 [==============================] - 0s 133us/step - loss: 1.1540 - acc: 0.3238
Epoch 981/1000
105/105 [==============================] - 0s 114us/step - loss: 1.1538 - acc: 0.3238
Epoch 982/1000
105/105 [==============================] - 0s 391us/step - loss: 1.1536 - acc: 0.3238
Epoch 983/1000
105/105 [==============================] - 0s 48us/step - loss: 1.1533 - acc: 0.3238
Epoch 984/1000
105/105 [==============================] - 0s 819us/step - loss: 1.1531 - acc: 0.3238
Epoch 985/1000
105/105 [==============================] - 0s 1ms/step - loss: 1.1529 - acc: 0.3238
Epoch 986/1000
105/105 [==============================] - 0s 48us/step - loss: 1.1527 - acc: 0.3333
Epoch 987/1000
105/105 [==============================] - 0s 305us/step - loss: 1.1525 - acc: 0.3333
Epoch 988/1000
105/105 [==============================] - 0s 57us/step - loss: 1.1523 - acc: 0.3333
Epoch 989/1000
105/105 [==============================] - 0s 48us/step - loss: 1.1521 - acc: 0.3

[array([[ 0.14246419],
        [-0.18267998],
        [ 0.4906421 ],
        [-1.4498768 ]], dtype=float32),
 array([-0.29535717], dtype=float32),
 array([[ 0.02525676, -0.42919675,  0.71019876]], dtype=float32),
 array([ 0.07057807,  0.33260804, -0.22667101], dtype=float32)]

In [33]:
W=model.get_weights()
w1=tf.constant(W[0])
b1=tf.constant(W[1])
w2=tf.constant(W[2])
b2=tf.constant(W[3])
x=tf.placeholder(tf.float32)
h=tf.maximum(0.0,tf.add(tf.matmul(x,w1),b1))
out=tf.nn.softmax(tf.add(tf.matmul(h,w2),b2))
error=[]

with tf.Session() as sess:
    for i in  range(105): 
        values={x:X[i,:].reshape(1,4)}
        print(sess.run(out,feed_dict=values),Y[i,])





[[0.32876107 0.38108417 0.29015473]] [0 0 1]
[[0.32608083 0.34809494 0.3258242 ]] [1 0 0]
[[0.32619512 0.3490793  0.32472563]] [0 0 1]
[[0.32916513 0.39326623 0.2775686 ]] [0 1 0]
[[0.32868522 0.42714798 0.24416676]] [1 0 0]
[[0.32736567 0.3605076  0.3121268 ]] [0 1 0]
[[0.32868522 0.42714798 0.24416676]] [1 0 0]
[[0.32655385 0.3522986  0.32114753]] [0 0 1]
[[0.32644212 0.35127342 0.32228446]] [0 1 0]
[[0.32157698 0.31825164 0.36017135]] [0 1 0]
[[0.3289971  0.38703245 0.28397042]] [0 1 0]
[[0.32868522 0.42714798 0.24416676]] [1 0 0]
[[0.32791063 0.3670888  0.30500057]] [0 1 0]
[[0.32619512 0.3490793  0.32472563]] [0 0 1]
[[0.32868522 0.42714798 0.24416676]] [1 0 0]
[[0.32816187 0.37057996 0.30125815]] [0 1 0]
[[0.32868522 0.42714798 0.24416676]] [1 0 0]
[[0.3287513  0.38087204 0.29037663]] [0 1 0]
[[0.32922897 0.39714065 0.27363044]] [0 0 1]
[[0.32638475 0.35075554 0.32285967]] [1 0 0]
[[0.32868522 0.42714798 0.24416676]] [1 0 0]
[[0.32882276 0.38247088 0.28870642]] [0 0 1]
[[0.328685