In [1]:
import tensorflow as tf
import numpy as np

In [2]:
Image=np.array([[3.0,5,3,4,1],[5,3,2,1,1],[3,1,4,1,0],[2,1,0,0,3]])
filter1=np.array([[3.0,1,2],[1,4,3],[1,1,0]])
print(Image)
print(filter1)

[[3. 5. 3. 4. 1.]
 [5. 3. 2. 1. 1.]
 [3. 1. 4. 1. 0.]
 [2. 1. 0. 0. 3.]]
[[3. 1. 2.]
 [1. 4. 3.]
 [1. 1. 0.]]


In [6]:
image_tf=tf.reshape(Image,[-1,4,5,1])
kernal_tf=tf.reshape(filter1,[3,3,1,1])
conv1=tf.nn.conv2d(image_tf,kernal_tf,strides=[1,1,1,1],padding="VALID")
with tf.Session() as sess:
    conv1_val=sess.run(conv1)
    pool1=tf.nn.max_pool(image_tf,ksize=[1,2,2,1],strides=[1,2,2,1],padding='VALID')
    pool1_val=sess.run(pool1)
    print(conv1_val.shape)
    print(conv1_val)
    print(pool1_val)

(1, 2, 3, 1)
[[[[47.]
   [45.]
   [29.]]

  [[44.]
   [34.]
   [17.]]]]
[[[[5.]
   [4.]]

  [[3.]
   [4.]]]]


[[3. 5. 3. 4. 1.]
 [5. 3. 2. 1. 1.]
 [3. 1. 4. 1. 0.]
 [2. 1. 0. 0. 3.]]
[[3. 2. 1.]
 [1. 4. 3.]
 [1. 1. 0.]]
(1, 2, 3, 1)
[[[[49.]
   [44.]
   [32.]]

  [[45.]
   [35.]
   [17.]]]]
(1, 2, 2, 1)
[[[[5.]
   [4.]]

  [[3.]
   [4.]]]]
